version: "3.7"
services:
  work:
    hostname: "WORKING!"
    build:
      context: ./docker/work
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./workspace:/root/workspace
  node:
    hostname: "Node!!"
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./workspace/node:/node
